name: GEOMETOR Fundamentals
motto: a GEOMETOR project
email: phi@geometor.com
logo: 
social:
  facebook: phiarchitect
  twitter: phi_architect
  linkedin: phiarchitect
  youtube: UCYzRQS16EBmsbKuyKMFHSFQ
  github: geometor
google_search: 
owa:
  siteId: 882d08be7f9e3d8a56342187c1a26a23
  trackPageView: true
  trackCLicks: false
  trackDomStream: false
description: 
org_type: Organization
geographic:
  latitude: 
  longitude: 
address:
  streetAddress: 
  postOfficeBoxNumber: 
  addressLocality: 
  addressRegion: OR
  postalCode: 
  addressCountry: US
image: 
