title: Fundamentals
default_lang: en
author:
  name: phi
  email: phi@illumiphi.com
taxonomies:
  - category
  - tag
metadata:
  description: 'a GEOMETOR project'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
logo: photon-logo.png
